### ISSUE TITLE
two questions about bottom sheets

### ISSUE THREAD

**Issue by kHRYSTAL** [android-cjj/BottomSheets#1]
你好 我想问下23.2包里Bottom Sheets的几个问题 
1.能否限制打开的最大高度，或者距离屏幕上方高度？
2.是不是和SlidePannel一样只能有一个抽屉手柄？我的意思就是比如Bottom Sheets里是三个可以切换的fragment，hideable=false，关闭的时候可见三个切换的Tab选项 点击可切换内部fragment，并支持拖拽

**Comment by 70kg** [comment]
@kHRYSTAL 1.代码里面似乎没有直接的这个方法，但是展开的高度是根据child的高度决定的
`mMinOffset = Math.max(0, mParentHeight - child.getHeight());
        if (mState == STATE_EXPANDED) {
            ViewCompat.offsetTopAndBottom(child, mMinOffset);`
想要限制高度就直接去限制child的高度好了
第二个不是很明白想表达什么意思，核心的代码都在那个Behavior里面，看看就明白了

**Comment by kHRYSTAL** [comment]
@70kg Thank you for your reply,第二个问题的意思是有个SlidingDrawer的控件有些类似BottomSheets，但是SlidingDrawer在隐藏时暴露在外面的区域只能充当handle，只具有拖拽和点击展开的作用，如果以这个handle作为父容器 内部的button点击事件是接收不到的，我想问的是BottomSheets能不能解决这个问题 并且允许通过子View 也就是我所说的Button，去实现拖拽

**Comment by 70kg** [comment]
@kHRYSTAL 在BottomSheets中暴露的区域就是你设置view的一部分，内部肯定是可以接受到事件的。

**Comment by kHRYSTAL** [comment]
@70kg Thank you so much :+1:
